export const ADD_EVENT_ACHIEVEMENTS = "ADD_EVENT_ACHIEVEMENTS";
export const ADD_WORK_EDUCATION = "ADD_WORK_EDUCATION";
export const EVENT_OR_WORK_ADDED = "EVENT_OR_WORK_ADDED";
export const REMOVE_LEFT_SIDE = "REMOVE_LEFT_SIDE";
