export const ADD_EVENT_ACHIEVEMENTS = "ADD_EVENT_ACHIEVEMENTS";
export const ADD_WORK_EDUCATION = "ADD_WORK_EDUCATION";
export const ADD_DATA = "ADD_DATA";
export const EVENT_OR_WORK_ADDED = "EVENT_OR_WORK_ADDED";
export const SCROLL_TO_ELEMENT = "SCROLL_TO_ELEMENT";
